### ISSUE TITLE
Unclear firmware instruction in README.md

### ISSUE THREAD

**Issue by abitrolly** [hughsie/lvfs-website#153]
1. As a non-member, I can not apply labels, and can not complete [this step](https://github.com/hughsie/lvfs-website#missing-firmware-at-lvfs).

Adding `[missing-firmware] ` to title can be an alternative. It can be then parsed by bot to add tags from issue description automatically. Flask app can do this. :)

2. Do I need to be a vendor or should my hardware to be in the list of supported devices to request firmware? Like https://pcsupport.lenovo.com/by/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x250/downloads

**Comment by hughsie** [comment]
It's a bit fuzzy; some hardware we know will be supported shortly, but Dell is really the only vendor that watches the list of requested firmware on the LVFS. I might add this to the LVFS itself with some kind of voting system, so for instance I can go to Lenovo and say "10,000 users want the t61 supported, what can you do?"

**Comment by abitrolly** [comment]
Can people repackage available firmware themselves and bill the vendors when it is ready? I think people in corporate environment would appreciate when something doesn't need to go through management to get permissions for allocating resources to work on that. And billing means that there is some king of proven customer agreement. And working system solving the problem is the best.

I think that for my Lenovo x250 I can build a cryptographically safe conversion toolchain from the https://pcsupport.lenovo.com/by/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x250/downloads to firmware and run it somewhere else,

**Comment by superm1** [comment]
It really depends on what the format of the UEFI capsule looks like to tell if this is possible.  For example it's entirely possible that the first bits of the capsule (after the header) are executable UEFI code.   I don't know if that happens in practice however.

You might compare the capsules to the executables on the website to see where commonality lies to develop some sort of tool that can repackage firmware.

Ideally if you're successful in this endeavor, please submit your patch to https://github.com/hughsie/fwupd/tree/master/contrib/firmware-packager which is currently available for the same function but with Thunderbolt binaries as shipped by Dell on support.dell.com.

**Comment by hughsie** [comment]
> Can people-repackage available firmware themselves

Yes.

> and bill the vendors when it is ready?

No. Unless you can find a pre-packaged .cap file somewhere, you'd have to sign the built capsule with the vendor signing key, which they're not going to give out to random contractors. There's also a whole heap of licencing, liability, IP, and (re-)distribution issues, and for this reason the LVFS only accepts firmware from the original OEM or an approved ODM rather than unaffiliated 3rd parties.

> And billing means that there is some king of proven customer agreement.

I think it's a bit more involved than just sending Lenovo an invoice :) I think if you do this with any big vendor you'll in the best case be ignored, and in the worst case get some kind of scary looking cease-and-desist from the vendor legal team.

>And working system solving the problem is the best.

I think the best way to get firmware for an unsupported system on the LVFS is to push for this with your vendor representative, be that the OEM directly or your OS provider e.g. Canonical or Red Hat. I know Red Hat has people pushing hardware companies right now, so if you have a TAM be sure to mention it to them. Lenovo are onboarding hardware fast now, and so the list of supported devices isn't the "final" one by any means.

**Comment by hughsie** [comment]
@abitrolly I've opened https://github.com/mrwnwttk/afulnx/issues/3 -- hopefully to get some dialog with the upstream author.

**Comment by abitrolly** [comment]
Subscribed. Thanks. I moved MSI firmware research into https://github.com/hughsie/lvfs-website/issues/159
