### ISSUE TITLE
Need to write some documentation about how to use estimated flash time

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#192]
Another vendor wants to use this, and it would be nice to have some LVFS HTML documentation we can point them at.

**Comment by hughsie** [comment]
I was also wondering if this makes sense for "offline" UEFI updates...

**Comment by superm1** [comment]
Hmm right now it's provided by the plugin. I'm not sure it can come in the metadata without some extra work.

**Comment by superm1** [comment]
Yikes, needing more than one reboot after the flash process starts is a scary feeling for an end user whether the system will come back or not.

The reason that it was done on the "plugin" rather than the metadata initially is that the update duration is typically a function of the tool, bus, etc.  The only consumer of this so far was the `dell_dock` plugin.  It sets different duration based on characteristics of how the devices were initialized and which bus.
Putting the information into the metadata couldn't capture that level of detail.

So that said I think that if an OEM is willing to fill this out in the metadata it makes sense to populate it in the daemon and show it in clients even for updates that take place in UEFI.

It does need some new metadata key and then fwupd will need to read the metadata key.  I'm thinking this would be best done as:
1. Key: `LVFS::InstallDuration`
2. Let the LVFS U/I insert this information if not already in the metadata.
3. Parse this information in the fwupd daemon only if the plugin didn't already declare an install duration.
4. Fwupd clients will need to make it clear that devices with the `needs-reboot` flag that number is "installation time on next boot" or something like that.  Otherwise it gets confusing that the update "applies" in 2 seconds from the client when it estimated 240 seconds!

**Comment by hughsie** [comment]
> is a scary feeling for an end user 

Tell me about it. Especially when it comes back with a blank screen a few times, then just restarts after doing the initial POST. I'll feed this back to them of course.

> the update duration is typically a function of the tool, bus

I think that's true, but I also think an EC update is going to be quicker to apply than an EC+ME+FW update, with both being just one efi binary.

> Key: LVFS::InstallDuration

`LVFS::` or `fwupd::` -- I know we've mixed and matched these over the last few months.

> Parse this information in the fwupd daemon only if the plugin didn't already declare an install duration

You think the plugin information always "wins"?

> clients will need to make it clear that devices with the needs-reboot flag that number is "installation time on next boot

I didn't think about that, good point. I'll have a play with a fwupd patch and see how it looks. If you could write a few lines about how to set it as a quirk I'd appreciate that.

Richard

**Comment by superm1** [comment]
> LVFS:: or fwupd:: -- I know we've mixed and matched these over the last few months.

No strong opinion.

> You think the plugin information always "wins"?

I guess after reading that the time may vary for EFI updates that only touch EC vs EC + FW that makes more sense that the metadata should take priority.

It will be interesting though that the install duration you get from get-devices varies based upon which CAB file fwupd thinks is the one to install.  Take this hypothetical (but I don't think too far fetched) scenario:

1. System is on UEFI 00.00.00.01
2. Metadata currently has UEFI 00.00.00.02 with `InstallDuration `of 60.
3. They open up gnome software and see the device and click it.  They see it says 00.00.00.02 is the new update and it's going to take a minute to install.
4. They remember hearing that 00.00.00.03 is out, so maybe they should refresh metadata.
5. Press the refresh button and now UEFI 00.00.00.03 shows up.  This actually has an `InstallDuration `of 120 but since gnome-software got the device previously it should be rendering the `InstallDuration `of 60.

Because of that scenario I almost wonder if you want fwupd's `InstallDuration `to be part of the release not the device.  If the plugin advertises `InstallDuration `then populate it into releases if it's empty.

The other option is to send a changed signal for this particular attribute of the device based on the candidate release.

> I didn't think about that, good point. I'll have a play with a fwupd patch and see how it looks. If you could write a few lines about how to set it as a quirk I'd appreciate that.

Since it has to land in fwupd, I'm not sure the right place to put it.  https://fwupd.org/lvfs/docs/metainfo is very specific to the metadata landing in CABs.

Maybe do we just need it in a markdown document somewhere in fwupd that explains how quirks work "in general"?  Similarly to what you did with the usage of GUIDs in different plugins maybe need to document which quirks plugins use in their code and in `src/` document project wide quirks supported.

**Comment by hughsie** [comment]
> maybe need to document which quirks plugins use in their code

I agree the per-plugin README.md is probably a better place for plugin-specific quirks, and maybe just use the main README.md for the others.

**Comment by hughsie** [comment]
> I almost wonder if you want fwupd's InstallDuration to be part of the release not the device

Agree: https://github.com/hughsie/fwupd/pull/843
