### ISSUE TITLE
XPS 9575 wants to update to Precision 5530 2-in-1 BIOS

### ISSUE THREAD

**Issue by josephlbarnett** [hughsie/lvfs-website#288]
My XPS 15 9575 2-in-1 is wanting to install https://fwupd.org/lvfs/device/6e7d6855-e280-4875-8b4c-4fc5934a4948

At least on the Dell website, they have separate BIOS installers with different version numbers and checksums:
https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=p93yr&oscode=wt64a&productcode=xps-15-9575-2-in-1-laptop
vs
https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=2rfmg&oscode=wt64a&productcode=precision-15-5530-2-in-1-laptop

**Comment by superm1** [comment]
Good eye in checking this; 9570 and 5530 should carry the same, but 9575 should not.  Let me pass this around internally to see if CHIDs are missing or something like that.

**Comment by superm1** [comment]
@hughsie Given the warning system in LVFS, I wonder if it's worth adding a check for "uniqueness" of ESRT GUIDs to avoid this in future.  I don't know that it would have actually caught this case, but generally seems like a good idea - especially across OEMs as a warning that you need a CHID.

(Probably wouldn't catch this case since XPS 9575 isn't formally supported with Linux and not posted to LVFS).

**Comment by hughsie** [comment]
> ESRT GUIDs

I guess I'd be up for that, I don't know how many false positives we'd get.

**Comment by superm1** [comment]
I hope the answer is 0.  If two OEMs do somehow have the same ESRT GUID and one doesn't have a CHID that seems like it's a recipe for disaster.

**Comment by superm1** [comment]
@josephlbarnett the update has been pulled.  Thanks for the catch.

FYI, if it had gone further and you tried to install it there were other safety mechanisms that would have prevented actually flashing it to the hardware.
