### ISSUE TITLE
Create a known issue for out of space

### ISSUE THREAD

**Issue by hughsie** [hughsie/lvfs-website#67]
For instance, see https://fwupd.org/lvfs/report/275

Maybe something like this:

URI: LVFS-Triaged-Issue:-Boot-Out-Of-Space
Summary: You don't have enough space on /boot
Solution: Free up some space on /boot

**Comment by superm1** [comment]
This needs to specifically match the ESP somehow.  Unfortunately `FWUP_ESP_MOUNTPOINT `is not exported.
I for example see the triaged issue it's matching right now is one that's errors related to running out of space on NVRAM.

**Comment by hughsie** [comment]
> related to running out of space on NVRAM

Do we want a known issue for this? Thanks for your brainpower!

**Comment by superm1** [comment]
My opinion is that for issues not understood, they're not really known.  I think they're good for us to look at and hypothesize what other information could be causing them to add into more verbose reports in the future (which is why we now capture for example EfivarVersion FwupdateVersion and SecureBoot).

That particular issue I referred to about running out of space on NVRAM I'm not sure if that means that efivarfs isn't compiled into the kernel (so those paths can't be touched) or if they really ran out of space on NVRAM.

**Comment by hughsie** [comment]
Agreed, ive deleted the test issue. Thanks.
