### ISSUE TITLE
Adding past firmware for 8Bitdo

### ISSUE THREAD

**Issue by niniendowarrior** [hughsie/lvfs-website#7]
Would it be possible to add the firmware for legacy and additional from their support page? http://support.8bitdo.com/

The new firmware (4.0 and 4.01) drops support for several platforms that other users may need.  While getting the dat file is possible, having them gpg signed and bundled in the cab files manually may be tricky.

**Comment by hughsie** [comment]
I think there are already old firmware versions, no? https://fwupd.org/lvfs/device/4fa94782-9ab0-531f-b038-a3e79ddf4b19

**Comment by niniendowarrior** [comment]
Hi!

That link does show the past firmware but this URL doesn't for some reason. https://fwupd.org/lvfs/device/7ff26c95-37dc-5485-b0a5-1cdaf2846da4
This one matches the device id of my FC30 Pro.

In addition, the link you post doesn't show FW 2.00 which is listed as Legacy in the support website link if you check the FC30 Pro firmware section.

Thanks for responding quickly!

**Comment by hughsie** [comment]
Ahh, this is because 8Bitdo changed their USB vendor ID in the latest firmware -- so to do downgrades you'd need to re-submit the older firmware files with the old *and new* vendor IDs. I'll have a think how we could do this on the LVFS rather than changing the old metainfo files.

It's up to 8Bitdo really if they want to support old firmware versions like 2.00, but if you do a PR against https://github.com/8BitdoTech I'm pretty sure he would merge it.

**Comment by niniendowarrior** [comment]
I think I'm a bit lost in terms of getting 8Bitdo to support old firmware since they host the actual firmware on their main website.  I don't expect them to really do any updates on the old 2.00 and below (1.71, etc).  I do think that for the LVFS site, hosting the past firmware would be really helpful.
Thanks!

**Comment by niniendowarrior** [comment]
Just an update, the way to apply the past firmware to the new devices is by using the updated tools with the .dat of the older firmware.  I suspect it's precisely because the device ids are different.

**Comment by hughsie** [comment]
I don't think 8bitdo are that interested in old versions, sorry. It has to be them to do the upload now.
