### ISSUE TITLE
Add sigul support

### ISSUE THREAD

**Issue by jordane** [hughsie/lvfs-website#87]
We need to add sigul support. Per discussion with @hughsie, this should be done before lvfs.linuxfoundation.org or similar is launched.

**Comment by hughsie** [comment]
Signing the metadata using sigul should be pretty straightforward; we just give it a `metadata.xml.gz` and it returns us a `metadata.xml.gz.asc` -- and then when we write metadata we'd just put it in a special place for a cron job to pick up, send to sigul and then move the detached signature into `downloads`.

The bit I'm not sure how to do is the cabinet archive. The signature of that is actually the detached signature of the firmware blob (e.g. `firmware.ROM`) added to the archive as `firmware.ROM.asc`. Because of the slightly unusual way Microsoft Windows Update builds the archive we really need to use GCab (which we do in the LVFS using GObjectIntrospection) rather than anything in pure python. I see two solutions here:

* We teach sigul about GCab, GObjectIntrospection and how to sign a firmware archive
* We do some kind of wrapper so that we ask sigul to sign `firmware.ROM` and then the LVFS/a cron job builds the destination .cab file and copies it into `downloads/`

I'm erring on solution 2 for simplicity.

@jordane so I can prototype something; a few questions:

* When you run the sigul command line on the client (e.g. to sign a metadata file) does it block until the destination file has been written?
* If there's an error while signing, does sigul return with a non-zero exit code and dump something on stderr?
* Do we know how long sigul is going to take? I know we guessed 5 minutes, but an actual number would be super from a UX point of view.
* In sigul, when you specify the `KEY` is it the `UID` (lfvs+firmware@linuxfoundation.org) it wants or the `KEY_ID` e.g. 183A73F1?
* Do you need to be a specific user on the client to use sigul? e.g. do we do it from the uwsgi user as a LVFS plugin in the flask process, or do we do it as a cron job as another user for example?

**Comment by jordane** [comment]
> I'm erring on solution 2 for simplicity.

I agree.

> When you run the sigul command line on the client (e.g. to sign a metadata file) does it block until the destination file has been written?

Yes, but see the last answer.

> If there's an error while signing, does sigul return with a non-zero exit code and dump something on stderr?

Yes, but see the last answer.

> Do we know how long sigul is going to take? I know we guessed 5 minutes, but an actual number would be super from a UX point of view.

It's basically instantaneous as soon as the data is transferred to the sigul server. Easily less than 30s unless the firmware files are large. 

> In sigul, when you specify the KEY is it the UID (lfvs+firmware@linuxfoundation.org) it wants or the KEY_ID e.g. 183A73F1?

You actually specify the (arbitrary) name sigul has for the key.

> Do you need to be a specific user on the client to use sigul? e.g. do we do it from the uwsgi user as a LVFS plugin in the flask process, or do we do it as a cron job as another user for example?

You don't need to be a specific user,  you only need to be a valid client and have the right passphrase. the Sigul client is actually Python, so we can use the client natively rather than shelling out. Once you've installed the sigul client package (named `sigul`), see /usr/share/sigul for the python code.

**Comment by hughsie** [comment]
> you only need to be a valid client and have the right passphrase

Would we hardcode the passphrase in the database?

**Comment by jordane** [comment]
> Would we hardcode the passphrase in the database?

We will put it in vault [1].

[1] https://www.vaultproject.io/

**Comment by hughsie** [comment]
> the Sigul client is actually Python, so we can use the client natively rather than shelling out

I asked Patrick (the upstream Sigul maintainer) about this just now, and he said "I'm not against making it a python API, but the current python functions are not stable at the moment" -- an advised we used the `sigul` binary directly.
